### ISSUE TITLE
ImportError: cannot import name 'axl' from 'ciscoaxl'

### ISSUE THREAD

**Issue by oletos7j** [levensailor/ciscoaxl#11]
Following the example of the docs, I'm unable to import axl.

Using Python 3.7.3 and ciscoaxl 0.158.

Traceback (most recent call last):
  File "./ciscoaxl.py", line 3, in <module>
    from ciscoaxl import axl
  File "/Users/oletos7j/Projects/onboarding/ciscoaxl.py", line 3, in <module>
    from ciscoaxl import axl
ImportError: cannot import name 'axl' from 'ciscoaxl'

**Comment by oletos7j** [comment]
I had a problem with my venv. Recreating it and deleting generated pyc files fixed it for me.
